[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/@prisma/client/*"]
  external_node_modules = ["@prisma/client"]
  node_bundler = "esbuild"
  timeout = "30s"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"